# EL&BE Gastro - Menu Data 2026
# Frissítve a 2026-os menü PDF-ek alapján

CATEGORIES = [
    {"id": "burger", "name_ro": "Burger", "name_en": "Burger", "name_hu": "Burger"},
    {"id": "pizza", "name_ro": "Pizza", "name_en": "Pizza", "name_hu": "Pizza"},
    {"id": "appetizer", "name_ro": "Antreu • Supă", "name_en": "Starters • Soup", "name_hu": "Előétel • Leves"},
    {"id": "salad", "name_ro": "Salate", "name_en": "Salads", "name_hu": "Saláták"},
    {"id": "pasta", "name_ro": "Paste", "name_en": "Pasta", "name_hu": "Tészta"},
    {"id": "main", "name_ro": "Fel Principal", "name_en": "Main Course", "name_hu": "Főétel"},
    {"id": "snack", "name_ro": "Snacks", "name_en": "Snacks", "name_hu": "Snack"},
    {"id": "dessert", "name_ro": "Desert", "name_en": "Dessert", "name_hu": "Desszert"},
    {"id": "coffee", "name_ro": "Cafele • Ceaiuri", "name_en": "Coffee • Tea", "name_hu": "Kávé • Tea"},
    {"id": "fresh", "name_ro": "Fresh-uri", "name_en": "Fresh Juices", "name_hu": "Friss levek"},
    {"id": "lemonade", "name_ro": "Limonade", "name_en": "Lemonades", "name_hu": "Limonádék"},
    {"id": "drink", "name_ro": "Răcoritoare", "name_en": "Soft Drinks", "name_hu": "Üdítők"},
    {"id": "virgin_cocktail", "name_ro": "Virgin Cocktails", "name_en": "Virgin Cocktails", "name_hu": "Virgin Koktélok"},
    {"id": "beer", "name_ro": "Bere", "name_en": "Beer", "name_hu": "Sör"},
    {"id": "cocktail", "name_ro": "Cocktailuri", "name_en": "Cocktails", "name_hu": "Koktélok"},
    {"id": "wine", "name_ro": "Vinuri", "name_en": "Wines", "name_hu": "Borok"},
    {"id": "short_drink", "name_ro": "Băuturi Scurte", "name_en": "Short Drinks", "name_hu": "Röviditalok"},
]

MENU_ITEMS = [
    # ─── BURGERI ───────────────────────────────────────────────
    {
        "id": "burger-1", "category": "burger", "price": 47,
        "name_ro": "Burger de Vită", "name_en": "Beef Burger", "name_hu": "Marhahús Burger",
        "desc_ro": "Chiflă, carne de vită black angus, pancetta, cheddar, salată, roșii, castraveți murați, ceapă roșie, cartofi pai, sos classic",
        "desc_en": "Bun, black angus beef, pancetta, cheddar, lettuce, tomatoes, pickles, red onion, fries, classic sauce",
        "desc_hu": "Zsemle, black angus marhahús, pancetta, cheddar, saláta, paradicsom, savanyú uborka, vöröshagyma, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-2", "category": "burger", "price": 45,
        "name_ro": "Burger cu Piept de Pui", "name_en": "Chicken Breast Burger", "name_hu": "Csirkemell Burger",
        "desc_ro": "Chiflă, piept de pui, pancetta, cheddar, salată, roșii, castraveți murați, ceapă roșie, cartofi pai, sos classic",
        "desc_en": "Bun, chicken breast, pancetta, cheddar, lettuce, tomatoes, pickles, red onion, fries, classic sauce",
        "desc_hu": "Zsemle, csirkemell, pancetta, cheddar, saláta, paradicsom, savanyú uborka, vöröshagyma, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-3", "category": "burger", "price": 48,
        "name_ro": "Burger de Vită Blue Cheese", "name_en": "Beef Blue Cheese Burger", "name_hu": "Marhahús Blue Cheese Burger",
        "desc_ro": "Chiflă, carne de vită black angus, jambon pădurea neagră, brânză cu mucegai, rucola, ceapă roșie, cartofi pai, sos classic",
        "desc_en": "Bun, black angus beef, black forest ham, blue cheese, rocket, red onion, fries, classic sauce",
        "desc_hu": "Zsemle, black angus marhahús, feketeerdei sonka, kéksajt, rukkola, vöröshagyma, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-4", "category": "burger", "price": 51,
        "name_ro": "Burger de Vită cu Ceapă Caramelizată", "name_en": "Beef Caramelized Onion Burger", "name_hu": "Marhahús Karamellizált Hagymás Burger",
        "desc_ro": "Chiflă, carne de vită black angus, ceapă caramelizată, rucola, pancetta, brânză camembert, cartofi pai, sos classic",
        "desc_en": "Bun, black angus beef, caramelized onion, rocket, pancetta, camembert cheese, fries, classic sauce",
        "desc_hu": "Zsemle, black angus marhahús, karamellizált hagyma, rukkola, pancetta, camembert sajt, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-5", "category": "burger", "price": 49,
        "name_ro": "Burger de Vită cu Sos de Ciuperci", "name_en": "Beef Mushroom Sauce Burger", "name_hu": "Marhahús Gombaszószos Burger",
        "desc_ro": "Chiflă, carne de vită black angus, rucola, pancetta, cheddar, roșii, cartofi pai, sos de ciuperci",
        "desc_en": "Bun, black angus beef, rocket, pancetta, cheddar, tomatoes, fries, mushroom sauce",
        "desc_hu": "Zsemle, black angus marhahús, rukkola, pancetta, cheddar, paradicsom, hasábburgonya, gombaszósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-6", "category": "burger", "price": 55,
        "name_ro": "Super Cheesy Burger", "name_en": "Super Cheesy Burger", "name_hu": "Super Cheesy Burger",
        "desc_ro": "Învelit în sos cheddar, chiflă, carne de vită black angus, ceapă caramelizată, cheddar, salată, roșii, castraveți murați, cartofi pai, sos classic",
        "desc_en": "Wrapped in cheddar sauce, bun, black angus beef, caramelized onion, cheddar, lettuce, tomatoes, pickles, fries, classic sauce",
        "desc_hu": "Cheddar szószban csomagolva, zsemle, black angus marhahús, karamellizált hagyma, cheddar, saláta, paradicsom, savanyú uborka, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-7", "category": "burger", "price": 62,
        "name_ro": "Smash Burger", "name_en": "Smash Burger", "name_hu": "Smash Burger",
        "desc_ro": "Chiflă, carne vită black angus, salată, ceapă caramelizată, sos smash, cedar, pancetta, cartofi pai",
        "desc_en": "Bun, black angus beef, lettuce, caramelized onion, smash sauce, cedar, pancetta, fries",
        "desc_hu": "Zsemle, black angus marhahús, saláta, karamellizált hagyma, smash szósz, cedar, pancetta, hasábburgonya",
        "weight": "130g/420g",
    },
    {
        "id": "burger-8", "category": "burger", "price": 48,
        "name_ro": "Brisket Burger", "name_en": "Brisket Burger", "name_hu": "Brisket Burger",
        "desc_ro": "Chiflă, piept de vită black angus, cheddar, rucola, coleslaw, castraveți murați, cartofi pai, sos classic",
        "desc_en": "Bun, black angus beef brisket, cheddar, rocket, coleslaw, pickles, fries, classic sauce",
        "desc_hu": "Zsemle, black angus marha brisket, cheddar, rukkola, coleslaw, savanyú uborka, hasábburgonya, classic szósz",
        "weight": "130g/420g",
    },
    {
        "id": "burger-9", "category": "burger", "price": 47,
        "name_ro": "Veggie Burger", "name_en": "Veggie Burger", "name_hu": "Veggie Burger",
        "desc_ro": "Chiflă, chiftea veggie, sos classic, cașcaval vegetal, salată, roșii, castraveți murați, cartofi pai",
        "desc_en": "Bun, veggie patty, classic sauce, vegan cheese, lettuce, tomatoes, pickles, fries",
        "desc_hu": "Zsemle, veggie fasírt, classic szósz, vegán sajt, saláta, paradicsom, savanyú uborka, hasábburgonya",
        "weight": "120g/420g",
    },
    {
        "id": "burger-10", "category": "burger", "price": 65,
        "name_ro": "Barbie Burger", "name_en": "Barbie Burger", "name_hu": "Barbie Burger",
        "desc_ro": "Chiflă, piept de vită black angus, foie gras (ficat de rață), rucola, roșii, cartofi pai, sos classic",
        "desc_en": "Bun, black angus beef brisket, foie gras (duck liver), rocket, tomatoes, fries, classic sauce",
        "desc_hu": "Zsemle, black angus marha brisket, foie gras (kacsaáj), rukkola, paradicsom, hasábburgonya, classic szósz",
        "weight": "150g/420g",
    },

    # ─── PIZZA ─────────────────────────────────────────────────
    {
        "id": "pizza-1", "category": "pizza", "price": 36,
        "name_ro": "Pizza EL&BE", "name_en": "Pizza EL&BE", "name_hu": "Pizza EL&BE",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, piept de pui, porumb, brânză cu mucegai, rucola",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, chicken breast, corn, blue cheese, rocket",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, csirkemell, kukorica, kéksajt, rukkola",
        "weight": "550g",
    },
    {
        "id": "pizza-2", "category": "pizza", "price": 33,
        "name_ro": "Margherita", "name_en": "Margherita", "name_hu": "Margherita",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, sos busuioc",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, basil sauce",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, bazsalikom szósz",
        "weight": "450g",
    },
    {
        "id": "pizza-3", "category": "pizza", "price": 33,
        "name_ro": "Salami", "name_en": "Salami", "name_hu": "Salami",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, salam",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, salami",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, szalámi",
        "weight": "450g",
    },
    {
        "id": "pizza-4", "category": "pizza", "price": 33,
        "name_ro": "Diavola", "name_en": "Diavola", "name_hu": "Diavola",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, salam picant, jalapeno",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, spicy salami, jalapeno",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, csípős szalámi, jalapeno",
        "weight": "450g",
    },
    {
        "id": "pizza-5", "category": "pizza", "price": 35,
        "name_ro": "Quattro Stagioni", "name_en": "Quattro Stagioni", "name_hu": "Quattro Stagioni",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, șuncă, salam, ciuperci, porumb",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, ham, salami, mushrooms, corn",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, sonka, szalámi, gomba, kukorica",
        "weight": "550g",
    },
    {
        "id": "pizza-6", "category": "pizza", "price": 36,
        "name_ro": "Quattro Formaggi", "name_en": "Quattro Formaggi", "name_hu": "Quattro Formaggi",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, brânză cu mucegai, edamer, parmesan, ceapă",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, blue cheese, edam, parmesan, onion",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, kéksajt, edami, parmesan, hagyma",
        "weight": "450g",
    },
    {
        "id": "pizza-7", "category": "pizza", "price": 36,
        "name_ro": "Kebab", "name_en": "Kebab", "name_hu": "Kebab",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, piept de pui, ceapă roșie, jalapeno, salată, roșii cherry, sos de usturoi",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, chicken breast, red onion, jalapeno, lettuce, cherry tomatoes, garlic sauce",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, csirkemell, vöröshagyma, jalapeno, saláta, koktélparadicsom, fokhagyma szósz",
        "weight": "550g",
    },
    {
        "id": "pizza-8", "category": "pizza", "price": 38,
        "name_ro": "Prosciutto di Parma", "name_en": "Prosciutto di Parma", "name_hu": "Prosciutto di Parma",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, șuncă parma, rucola, roșii cherry, parmesan",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, parma ham, rocket, cherry tomatoes, parmesan",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, pármai sonka, rukkola, koktélparadicsom, parmesan",
        "weight": "450g",
    },
    {
        "id": "pizza-9", "category": "pizza", "price": 34,
        "name_ro": "Prosciutto e Funghi", "name_en": "Prosciutto e Funghi", "name_hu": "Prosciutto e Funghi",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, șuncă, ciuperci",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, ham, mushrooms",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, sonka, gomba",
        "weight": "480g",
    },
    {
        "id": "pizza-10", "category": "pizza", "price": 38,
        "name_ro": "Quattro Carni", "name_en": "Quattro Carni", "name_hu": "Quattro Carni",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, piept de pui, brisket de vită, șuncă, salam",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, chicken breast, beef brisket, ham, salami",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, csirkemell, marha brisket, sonka, szalámi",
        "weight": "550g",
    },
    {
        "id": "pizza-11", "category": "pizza", "price": 38,
        "name_ro": "Brisket Calzone", "name_en": "Brisket Calzone", "name_hu": "Brisket Calzone",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, brisket de vită, blue cheese, salată mixtă, house dressing",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, beef brisket, blue cheese, mixed salad, house dressing",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, marha brisket, kéksajt, vegyes saláta, house dressing",
        "weight": "550g",
    },
    {
        "id": "pizza-12", "category": "pizza", "price": 38,
        "name_ro": "Pizza Țărănească", "name_en": "Country Pizza", "name_hu": "Parasztos Pizza",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella, cârnaț, ceapă, salam picant, ardei kapia, sos de usturoi",
        "desc_en": "Homemade dough, tomato sauce, mozzarella, sausage, onion, spicy salami, kapia pepper, garlic sauce",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella, kolbász, hagyma, csípős szalámi, kápia paprika, fokhagyma szósz",
        "weight": "550g",
    },
    {
        "id": "pizza-13", "category": "pizza", "price": 34,
        "name_ro": "Vegetarian", "name_en": "Vegetarian", "name_hu": "Vegetáriánus",
        "desc_ro": "Aluat de casă, sos de roșii, mozzarella sau cașcaval vegetal, broccoli, ciuperci, ardei, ceapă, porumb, roșii cherry",
        "desc_en": "Homemade dough, tomato sauce, mozzarella or vegan cheese, broccoli, mushrooms, pepper, onion, corn, cherry tomatoes",
        "desc_hu": "Házi tészta, paradicsom szósz, mozzarella vagy vegán sajt, brokkoli, gomba, paprika, hagyma, kukorica, koktélparadicsom",
        "weight": "550g",
    },
    {
        "id": "pizza-14", "category": "pizza", "price": 19,
        "name_ro": "Focaccia", "name_en": "Focaccia", "name_hu": "Focaccia",
        "desc_ro": "Aluat, ulei de măsline, parmesan",
        "desc_en": "Dough, olive oil, parmesan",
        "desc_hu": "Tészta, olívaolaj, parmesan",
        "weight": "260g",
    },

    # ─── ANTREU / SUPĂ ────────────────────────────────────────
    {
        "id": "appetizer-1", "category": "appetizer", "price": 20,
        "name_ro": "Supă / Ciorbă Zilei", "name_en": "Soup of the Day", "name_hu": "Napi Leves",
        "desc_ro": "450ml",
        "desc_en": "450ml",
        "desc_hu": "450ml",
        "weight": "450ml",
    },
    {
        "id": "appetizer-2", "category": "appetizer", "price": 50,
        "name_ro": "Măduvă de Vită Coaptă în Os", "name_en": "Roasted Bone Marrow", "name_hu": "Sült Velős Csont",
        "desc_ro": "Baghetă, salată de microplante, capere, roșii cherry, ceapă roșie",
        "desc_en": "Baguette, microgreens salad, capers, cherry tomatoes, red onion",
        "desc_hu": "Bagett, microgreens saláta, kapribogyó, koktélparadicsom, vöröshagyma",
        "weight": "600g/80g",
    },
    {
        "id": "appetizer-3", "category": "appetizer", "price": 42,
        "name_ro": "Camembert pe Grill", "name_en": "Grilled Camembert", "name_hu": "Grillezett Camembert",
        "desc_ro": "Sos de fructe de pădure, șuncă parma, baghetă",
        "desc_en": "Berry sauce, parma ham, baguette",
        "desc_hu": "Erdei gyümölcs szósz, pármai sonka, bagett",
        "weight": "120g/175g",
    },
    {
        "id": "appetizer-4", "category": "appetizer", "price": 32,
        "name_ro": "Foccacia cu Jambon Pădurea Neagră", "name_en": "Focaccia with Black Forest Ham", "name_hu": "Focaccia Feketeerdei Sonkával",
        "desc_ro": "Roșii cherry, rucola, parmesan, ulei de măsline, maioneză cu trufe/ciuperci",
        "desc_en": "Cherry tomatoes, rocket, parmesan, olive oil, truffle/mushroom mayo",
        "desc_hu": "Koktélparadicsom, rukkola, parmesan, olívaolaj, szarvasgomba/gomba majonéz",
        "weight": "25g/200g",
    },
    {
        "id": "appetizer-5", "category": "appetizer", "price": 65,
        "name_ro": "Ficat de Rață cu Ceapă Caramelizată", "name_en": "Duck Liver with Caramelized Onion", "name_hu": "Kacsamáj Karamellizált Hagymával",
        "desc_ro": "Baghetă cu unt",
        "desc_en": "Baguette with butter",
        "desc_hu": "Vajas bagett",
        "weight": "150g",
    },

    # ─── SALATE ───────────────────────────────────────────────
    {
        "id": "salad-1", "category": "salad", "price": 37,
        "name_ro": "Salată cu Piept de Pui", "name_en": "Chicken Breast Salad", "name_hu": "Csirkemell Saláta",
        "desc_ro": "Piept de pui, salată mixtă, pancetta, roșii cherry, porumb, ardei, parmesan, baghetă, house dressing",
        "desc_en": "Chicken breast, mixed salad, pancetta, cherry tomatoes, corn, pepper, parmesan, baguette, house dressing",
        "desc_hu": "Csirkemell, vegyes saláta, pancetta, koktélparadicsom, kukorica, paprika, parmesan, bagett, house dressing",
        "weight": "130g/270g",
    },
    {
        "id": "salad-2", "category": "salad", "price": 40,
        "name_ro": "Salată Brisket", "name_en": "Brisket Salad", "name_hu": "Brisket Saláta",
        "desc_ro": "Piept de vită, salată rucola, roșii cherry, ceapă roșie, ardei, ou fiert, parmesan, baghetă, house dressing",
        "desc_en": "Beef brisket, rocket salad, cherry tomatoes, red onion, pepper, boiled egg, parmesan, baguette, house dressing",
        "desc_hu": "Marha brisket, rukkola saláta, koktélparadicsom, vöröshagyma, paprika, főtt tojás, parmesan, bagett, house dressing",
        "weight": "100g/270g",
    },
    {
        "id": "salad-3", "category": "salad", "price": 42,
        "name_ro": "Salată Caesar cu Crispy de Pui", "name_en": "Caesar Salad with Crispy Chicken", "name_hu": "Caesar Saláta Ropogós Csirkével",
        "desc_ro": "Salată, parmezan, crutoane, anșoa, sos caesar",
        "desc_en": "Lettuce, parmesan, croutons, anchovy, caesar sauce",
        "desc_hu": "Saláta, parmesan, krutón, szardella, caesar szósz",
        "weight": "110g/270g",
    },
    {
        "id": "salad-4", "category": "salad", "price": 45,
        "name_ro": "Salată cu Somon Fumé", "name_en": "Smoked Salmon Salad", "name_hu": "Füstölt Lazac Saláta",
        "desc_ro": "Salată rucola, broccoli, ou fiert, baghetă, măsline, roșii uscate, dressing",
        "desc_en": "Rocket salad, broccoli, boiled egg, baguette, olives, dried tomatoes, dressing",
        "desc_hu": "Rukkola saláta, brokkoli, főtt tojás, bagett, olívabogyó, szárított paradicsom, dressing",
        "weight": "120g/270g",
    },

    # ─── PASTE ────────────────────────────────────────────────
    {
        "id": "pasta-1", "category": "pasta", "price": 46,
        "name_ro": "Paste cu Creveți", "name_en": "Shrimp Pasta", "name_hu": "Garnélás Tészta",
        "desc_ro": "Roșii cherry, unt, usturoi, ciuperci de pădure, parmesan, pătrunjel",
        "desc_en": "Cherry tomatoes, butter, garlic, forest mushrooms, parmesan, parsley",
        "desc_hu": "Koktélparadicsom, vaj, fokhagyma, erdei gomba, parmesan, petrezselyem",
        "weight": "80g/400g",
    },
    {
        "id": "pasta-2", "category": "pasta", "price": 39,
        "name_ro": "Paste Gratinate", "name_en": "Gratin Pasta", "name_hu": "Gratin Tészta",
        "desc_ro": "Piept de pui, smântână dulce, parmesan, mozzarella",
        "desc_en": "Chicken breast, sweet cream, parmesan, mozzarella",
        "desc_hu": "Csirkemell, tejszín, parmesan, mozzarella",
        "weight": "80g/400g",
    },
    {
        "id": "pasta-3", "category": "pasta", "price": 38,
        "name_ro": "Risotto cu Hribi de Pădure", "name_en": "Forest Mushroom Risotto", "name_hu": "Erdei Gombás Rizottó",
        "desc_ro": "Unt, parmesan, pătrunjel",
        "desc_en": "Butter, parmesan, parsley",
        "desc_hu": "Vaj, parmesan, petrezselyem",
        "weight": "80g/400g",
    },
    {
        "id": "pasta-4", "category": "pasta", "price": 46,
        "name_ro": "Risotto cu Creveți și Roșii Cherry", "name_en": "Shrimp & Cherry Tomato Risotto", "name_hu": "Garnélás Koktélparadicsmos Rizottó",
        "desc_ro": "Unt, parmesan, pătrunjel",
        "desc_en": "Butter, parmesan, parsley",
        "desc_hu": "Vaj, parmesan, petrezselyem",
        "weight": "80g/400g",
    },
    {
        "id": "pasta-5", "category": "pasta", "price": 32,
        "name_ro": "Garganelli cu Ou & Slănină de Mangalița", "name_en": "Garganelli with Egg & Mangalitza Bacon", "name_hu": "Garganelli Tojással & Mangalica Szalonnával",
        "desc_ro": "Varză murată, parmezan",
        "desc_en": "Sauerkraut, parmesan",
        "desc_hu": "Savanyú káposzta, parmesan",
        "weight": "50g/400g",
    },

    # ─── FEL PRINCIPAL ────────────────────────────────────────
    {
        "id": "main-1", "category": "main", "price": 50,
        "name_ro": "Mac & Cheese cu Piept de Pui", "name_en": "Mac & Cheese with Chicken Breast", "name_hu": "Mac & Cheese Csirkemellel",
        "desc_ro": "Paste, sos cheddar, pancetta crocant",
        "desc_en": "Pasta, cheddar sauce, crispy pancetta",
        "desc_hu": "Tészta, cheddar szósz, ropogós pancetta",
        "weight": "220g/250g",
    },
    {
        "id": "main-2", "category": "main", "price": 55,
        "name_ro": "Steak din Piept de Pui", "name_en": "Chicken Breast Steak", "name_hu": "Csirkemell Steak",
        "desc_ro": "Cartofi colorați, broccoli, ceapă Lyon, sos brun",
        "desc_en": "Colored potatoes, broccoli, Lyon onion, brown sauce",
        "desc_hu": "Színes burgonya, brokkoli, lyon hagyma, barna szósz",
        "weight": "220g/250g",
    },
    {
        "id": "main-3", "category": "main", "price": 71,
        "name_ro": "Scăriță de Porc cu Sos BBQ", "name_en": "Pork Ribs with BBQ Sauce", "name_hu": "Sertésborda BBQ Szósszal",
        "desc_ro": "Cartofi wedges, salată coleslaw",
        "desc_en": "Potato wedges, coleslaw salad",
        "desc_hu": "Wedges burgonya, coleslaw saláta",
        "weight": "350g/250g",
    },
    {
        "id": "main-4", "category": "main", "price": 65,
        "name_ro": "Mușchiuleț de Porc cu Sos de Hribi", "name_en": "Pork Tenderloin with Mushroom Sauce", "name_hu": "Sertésszűz Gombaszósszal",
        "desc_ro": "Risotto, unt, parmesan, pătrunjel",
        "desc_en": "Risotto, butter, parmesan, parsley",
        "desc_hu": "Rizottó, vaj, parmesan, petrezselyem",
        "weight": "180g/250g",
    },
    {
        "id": "main-5", "category": "main", "price": 60,
        "name_ro": "Obrăjori de Porc", "name_en": "Pork Cheeks", "name_hu": "Sertés Pofahús",
        "desc_ro": "Cartofi piure, sos brun, castraveți murați",
        "desc_en": "Mashed potatoes, brown sauce, pickles",
        "desc_hu": "Burgonyapüré, barna szósz, savanyú uborka",
        "weight": "500g/250g",
    },
    {
        "id": "main-6", "category": "main", "price": 110,
        "name_ro": "Tournedos Rossini", "name_en": "Tournedos Rossini", "name_hu": "Tournedos Rossini",
        "desc_ro": "Mușchi de vită, foie gras, cartofi piure, sos de hribi",
        "desc_en": "Beef tenderloin, foie gras, mashed potatoes, mushroom sauce",
        "desc_hu": "Marha szűzpecsenye, foie gras, burgonyapüré, gombaszósz",
        "weight": "200g/250g",
    },
    {
        "id": "main-7", "category": "main", "price": 60,
        "name_ro": "Vegetarian/Vegan", "name_en": "Vegetarian/Vegan", "name_hu": "Vegetáriánus/Vegán",
        "desc_ro": "Chips din cartofi dulci, broccoli, camembert/chiftea vegan",
        "desc_en": "Sweet potato chips, broccoli, camembert/vegan patty",
        "desc_hu": "Édesburgonya chips, brokkoli, camembert/vegán fasírt",
        "weight": "125g/250g",
    },
    {
        "id": "main-8", "category": "main", "price": 65,
        "name_ro": "Somon pe Grill", "name_en": "Grilled Salmon", "name_hu": "Grillezett Lazac",
        "desc_ro": "Cartofi colorați, sos caesar, usturoi, pătrunjel, unt, lămâie",
        "desc_en": "Colored potatoes, caesar sauce, garlic, parsley, butter, lemon",
        "desc_hu": "Színes burgonya, caesar szósz, fokhagyma, petrezselyem, vaj, citrom",
        "weight": "180g/250g",
    },

    # ─── SNACKS ───────────────────────────────────────────────
    {
        "id": "snack-1", "category": "snack", "price": 12,
        "name_ro": "Cartofi Pai", "name_en": "French Fries", "name_hu": "Hasábburgonya",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200g",
    },
    {
        "id": "snack-2", "category": "snack", "price": 18,
        "name_ro": "Cartofi Dulci", "name_en": "Sweet Potato Fries", "name_hu": "Édesburgonya Hasáb",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200g",
    },
    {
        "id": "snack-3", "category": "snack", "price": 43,
        "name_ro": "Aripioare de Pui cu Sos de Usturoi și Cartofi Pai", "name_en": "Chicken Wings with Garlic Sauce and Fries", "name_hu": "Csirkeszárny Fokhagyma Szósszal és Hasábburgonyával",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "230g/200g",
    },
    {
        "id": "snack-4", "category": "snack", "price": 45,
        "name_ro": "Crispy Strips cu Sos de Usturoi și Cartofi Pai", "name_en": "Crispy Strips with Garlic Sauce and Fries", "name_hu": "Crispy Strips Fokhagyma Szósszal és Hasábburgonyával",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "230g/200g",
    },
    {
        "id": "snack-5", "category": "snack", "price": 44,
        "name_ro": "Creveți Pane cu Legume Tempura", "name_en": "Breaded Shrimp with Tempura Vegetables", "name_hu": "Bundás Garnéla Tempura Zöldségekkel",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "150g/150g",
    },

    # ─── DESERT ───────────────────────────────────────────────
    {
        "id": "dessert-1", "category": "dessert", "price": 19,
        "name_ro": "Cheesecake cu Gem de Afine", "name_en": "Blueberry Cheesecake", "name_hu": "Áfonyás Sajttorta",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "150g",
    },
    {
        "id": "dessert-2", "category": "dessert", "price": 21,
        "name_ro": "Lava Cake cu Înghețată de Vanilie", "name_en": "Lava Cake with Vanilla Ice Cream", "name_hu": "Lava Cake Vaníliafagyival",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200g",
    },
    {
        "id": "dessert-3", "category": "dessert", "price": 18,
        "name_ro": "Desertul Zilei", "name_en": "Dessert of the Day", "name_hu": "Napi Desszert",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200g",
    },
    {
        "id": "dessert-4", "category": "dessert", "price": 8,
        "name_ro": "Înghețată Artizanală", "name_en": "Artisan Ice Cream", "name_hu": "Kézműves Fagylalt",
        "desc_ro": "per 50g", "desc_en": "per 50g", "desc_hu": "50g-ként",
        "weight": "50g",
    },

    # ─── CAFELE / CEAIURI ─────────────────────────────────────
    {
        "id": "coffee-1", "category": "coffee", "price": 8,
        "name_ro": "Espresso / Espresso Lung", "name_en": "Espresso / Long Espresso", "name_hu": "Eszpresszó / Hosszú Eszpresszó",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "30ml",
    },
    {
        "id": "coffee-2", "category": "coffee", "price": 13,
        "name_ro": "Latte Simplă", "name_en": "Latte", "name_hu": "Latte",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },
    {
        "id": "coffee-3", "category": "coffee", "price": 15,
        "name_ro": "Latte cu Cocos", "name_en": "Coconut Latte", "name_hu": "Kókuszos Latte",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },
    {
        "id": "coffee-4", "category": "coffee", "price": 15,
        "name_ro": "Latte cu Caramel", "name_en": "Caramel Latte", "name_hu": "Karamelles Latte",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },
    {
        "id": "coffee-5", "category": "coffee", "price": 12,
        "name_ro": "Cappuccino", "name_en": "Cappuccino", "name_hu": "Cappuccino",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "100ml",
    },
    {
        "id": "coffee-6", "category": "coffee", "price": 15,
        "name_ro": "Ciocolată Caldă Albă/Neagră", "name_en": "White/Dark Hot Chocolate", "name_hu": "Fehér/Fekete Forró Csokoládé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },
    {
        "id": "coffee-7", "category": "coffee", "price": 7,
        "name_ro": "Ceai", "name_en": "Tea", "name_hu": "Tea",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "250ml",
    },
    {
        "id": "coffee-8", "category": "coffee", "price": 16,
        "name_ro": "Iced Coffee", "name_en": "Iced Coffee", "name_hu": "Jeges Kávé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },

    # ─── FRESH-URI ────────────────────────────────────────────
    {
        "id": "fresh-1", "category": "fresh", "price": 16,
        "name_ro": "Fresh Portocale", "name_en": "Orange Juice", "name_hu": "Narancslé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "300ml",
    },
    {
        "id": "fresh-2", "category": "fresh", "price": 16,
        "name_ro": "Fresh Grapefruit", "name_en": "Grapefruit Juice", "name_hu": "Grépfrútlé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "300ml",
    },
    {
        "id": "fresh-3", "category": "fresh", "price": 18,
        "name_ro": "Fresh Mixt", "name_en": "Mixed Fresh Juice", "name_hu": "Vegyes Gyümölcslé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "350ml",
    },
    {
        "id": "fresh-4", "category": "fresh", "price": 20,
        "name_ro": "Smoothie", "name_en": "Smoothie", "name_hu": "Smoothie",
        "desc_ro": "Kale, căpșuni și banane",
        "desc_en": "Kale, strawberries and banana",
        "desc_hu": "Kelkáposzta, eper és banán",
        "weight": "250ml",
    },

    # ─── LIMONADE ─────────────────────────────────────────────
    {
        "id": "lemonade-1", "category": "lemonade", "price": 20,
        "name_ro": "Limonadă Yuzu Simplă", "name_en": "Yuzu Lemonade", "name_hu": "Yuzu Limonádé",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "450ml",
    },
    {
        "id": "lemonade-2", "category": "lemonade", "price": 20,
        "name_ro": "Mango cu Pepene Galben", "name_en": "Mango & Honeydew", "name_hu": "Mangó & Sárgadinnye",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "450ml",
    },
    {
        "id": "lemonade-3", "category": "lemonade", "price": 20,
        "name_ro": "Kiwi cu Pepene Galben", "name_en": "Kiwi & Honeydew", "name_hu": "Kiwi & Sárgadinnye",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "450ml",
    },
    {
        "id": "lemonade-4", "category": "lemonade", "price": 20,
        "name_ro": "Zmeură cu Hibiscus", "name_en": "Raspberry & Hibiscus", "name_hu": "Málna & Hibiszkusz",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "450ml",
    },

    # ─── RĂCORITOARE ──────────────────────────────────────────
    {
        "id": "drink-1", "category": "drink", "price": 10,
        "name_ro": "Pepsi 330ml", "name_en": "Pepsi 330ml", "name_hu": "Pepsi 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-2", "category": "drink", "price": 10,
        "name_ro": "Pepsi Max 330ml", "name_en": "Pepsi Max 330ml", "name_hu": "Pepsi Max 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-3", "category": "drink", "price": 10,
        "name_ro": "Pepsi Twist 330ml", "name_en": "Pepsi Twist 330ml", "name_hu": "Pepsi Twist 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-4", "category": "drink", "price": 10,
        "name_ro": "Mirinda 330ml", "name_en": "Mirinda 330ml", "name_hu": "Mirinda 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-5", "category": "drink", "price": 10,
        "name_ro": "7 Up 330ml", "name_en": "7 Up 330ml", "name_hu": "7 Up 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-6", "category": "drink", "price": 9,
        "name_ro": "Mountain Dew 250ml", "name_en": "Mountain Dew 250ml", "name_hu": "Mountain Dew 250ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "250ml",
    },
    {
        "id": "drink-7", "category": "drink", "price": 10,
        "name_ro": "Evervess Bitter 250ml", "name_en": "Evervess Bitter 250ml", "name_hu": "Evervess Bitter 250ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "250ml",
    },
    {
        "id": "drink-8", "category": "drink", "price": 10,
        "name_ro": "Prigat 250ml", "name_en": "Prigat 250ml", "name_hu": "Prigat 250ml",
        "desc_ro": "Căpșuni și banane, piersică, portocale, kiwi",
        "desc_en": "Strawberry & banana, peach, orange, kiwi",
        "desc_hu": "Eper & banán, őszibarack, narancs, kiwi",
        "weight": "250ml",
    },
    {
        "id": "drink-9", "category": "drink", "price": 12,
        "name_ro": "Lipton 500ml", "name_en": "Lipton 500ml", "name_hu": "Lipton 500ml",
        "desc_ro": "Piersici, ceai verde, lămâie, zmeură",
        "desc_en": "Peach, green tea, lemon, raspberry",
        "desc_hu": "Őszibarack, zöld tea, citrom, málna",
        "weight": "500ml",
    },
    {
        "id": "drink-10", "category": "drink", "price": 16,
        "name_ro": "Redbull 250ml", "name_en": "Redbull 250ml", "name_hu": "Redbull 250ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "250ml",
    },
    {
        "id": "drink-11", "category": "drink", "price": 9,
        "name_ro": "Apă Plată 330ml", "name_en": "Still Water 330ml", "name_hu": "Szénsavmentes Víz 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-12", "category": "drink", "price": 14,
        "name_ro": "Apă Plată 750ml", "name_en": "Still Water 750ml", "name_hu": "Szénsavmentes Víz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "drink-13", "category": "drink", "price": 9,
        "name_ro": "Apă Carbogazoasă 330ml", "name_en": "Sparkling Water 330ml", "name_hu": "Szénsavas Víz 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "drink-14", "category": "drink", "price": 14,
        "name_ro": "Apă Carbogazoasă 750ml", "name_en": "Sparkling Water 750ml", "name_hu": "Szénsavas Víz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "drink-15", "category": "drink", "price": 16,
        "name_ro": "Apple Juice 330ml", "name_en": "Apple Juice 330ml", "name_hu": "Almalé 330ml",
        "desc_ro": "Mango, mere, ghimbir",
        "desc_en": "Mango, apple, ginger",
        "desc_hu": "Mangó, alma, gyömbér",
        "weight": "330ml",
    },
    {
        "id": "drink-16", "category": "drink", "price": 11,
        "name_ro": "Aqua Zmeură 330ml", "name_en": "Aqua Raspberry 330ml", "name_hu": "Aqua Málna 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },

    # ─── VIRGIN COCKTAILS ─────────────────────────────────────
    {
        "id": "virgin-1", "category": "virgin_cocktail", "price": 22,
        "name_ro": "Pomelo Lime", "name_en": "Pomelo Lime", "name_hu": "Pomelo Lime",
        "desc_ro": "Sirop grenadine, sirop lime, pepsi, gheață",
        "desc_en": "Grenadine syrup, lime syrup, pepsi, ice",
        "desc_hu": "Grenadine szirup, lime szirup, pepsi, jég",
        "weight": "250ml",
    },
    {
        "id": "virgin-2", "category": "virgin_cocktail", "price": 22,
        "name_ro": "Mohito Virgin", "name_en": "Virgin Mohito", "name_hu": "Virgin Mohito",
        "desc_ro": "Lime, mentă, cocktail mix, gheață, apă carbogazificată",
        "desc_en": "Lime, mint, cocktail mix, ice, sparkling water",
        "desc_hu": "Lime, menta, cocktail mix, jég, szénsavas víz",
        "weight": "250ml",
    },
    {
        "id": "virgin-3", "category": "virgin_cocktail", "price": 22,
        "name_ro": "Grandma's Cake", "name_en": "Grandma's Cake", "name_hu": "Grandma's Cake",
        "desc_ro": "Scorțișoare, suc de merișoare, suc de mere, sirop de caramel, gheață",
        "desc_en": "Cinnamon, cranberry juice, apple juice, caramel syrup, ice",
        "desc_hu": "Fahéj, vörösáfonya lé, almalé, karamell szirup, jég",
        "weight": "250ml",
    },

    # ─── BERE ─────────────────────────────────────────────────
    {
        "id": "beer-1", "category": "beer", "price": 11,
        "name_ro": "Carlsberg 500ml", "name_en": "Carlsberg 500ml", "name_hu": "Carlsberg 500ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "500ml",
    },
    {
        "id": "beer-2", "category": "beer", "price": 10,
        "name_ro": "Tuborg 500ml", "name_en": "Tuborg 500ml", "name_hu": "Tuborg 500ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "500ml",
    },
    {
        "id": "beer-3", "category": "beer", "price": 11,
        "name_ro": "Tuborg F.A. 500ml", "name_en": "Tuborg F.A. 500ml", "name_hu": "Tuborg F.A. 500ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "500ml",
    },
    {
        "id": "beer-4", "category": "beer", "price": 10,
        "name_ro": "Draft Tuborg 400ml", "name_en": "Draft Tuborg 400ml", "name_hu": "Draft Tuborg 400ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "400ml",
    },
    {
        "id": "beer-5", "category": "beer", "price": 8,
        "name_ro": "Draft Tuborg 250ml", "name_en": "Draft Tuborg 250ml", "name_hu": "Draft Tuborg 250ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "250ml",
    },
    {
        "id": "beer-6", "category": "beer", "price": 15,
        "name_ro": "Clausthaler F.A. Lemon 330ml", "name_en": "Clausthaler F.A. Lemon 330ml", "name_hu": "Clausthaler F.A. Lemon 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "beer-7", "category": "beer", "price": 15,
        "name_ro": "Corona 330ml", "name_en": "Corona 330ml", "name_hu": "Corona 330ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "330ml",
    },
    {
        "id": "beer-8", "category": "beer", "price": 15,
        "name_ro": "Bucur Blondă 350ml", "name_en": "Bucur Blonde 350ml", "name_hu": "Bucur Szőke 350ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "350ml",
    },

    # ─── COCKTAILURI ──────────────────────────────────────────
    {
        "id": "cocktail-1", "category": "cocktail", "price": 27,
        "name_ro": "Aperol Spritz", "name_en": "Aperol Spritz", "name_hu": "Aperol Spritz",
        "desc_ro": "Prosecco, aperol, gheață, apă carbogazificată",
        "desc_en": "Prosecco, aperol, ice, sparkling water",
        "desc_hu": "Prosecco, aperol, jég, szénsavas víz",
        "weight": "300ml",
    },
    {
        "id": "cocktail-2", "category": "cocktail", "price": 25,
        "name_ro": "Coconut Cramberry", "name_en": "Coconut Cramberry", "name_hu": "Coconut Cramberry",
        "desc_ro": "Rom cu cocos, suc de merișoare, gheață",
        "desc_en": "Coconut rum, cranberry juice, ice",
        "desc_hu": "Kókuszos rum, vörösáfonya lé, jég",
        "weight": "250ml",
    },
    {
        "id": "cocktail-3", "category": "cocktail", "price": 25,
        "name_ro": "Mojito", "name_en": "Mojito", "name_hu": "Mojito",
        "desc_ro": "Rom, lime, mentă, apă carbogazoasă, sirop de zahăr, gheață",
        "desc_en": "Rum, lime, mint, sparkling water, sugar syrup, ice",
        "desc_hu": "Rum, lime, menta, szénsavas víz, cukorszirup, jég",
        "weight": "250ml",
    },
    {
        "id": "cocktail-4", "category": "cocktail", "price": 26,
        "name_ro": "Hugo", "name_en": "Hugo", "name_hu": "Hugo",
        "desc_ro": "Frizzante, sirop flori de soc, lime, mentă, apă carbogazoasă, gheață",
        "desc_en": "Frizzante, elderflower syrup, lime, mint, sparkling water, ice",
        "desc_hu": "Frizzante, bodza szirup, lime, menta, szénsavas víz, jég",
        "weight": "400ml",
    },
    {
        "id": "cocktail-5", "category": "cocktail", "price": 26,
        "name_ro": "Lillet", "name_en": "Lillet", "name_hu": "Lillet",
        "desc_ro": "Schweppes, lillet, gheață",
        "desc_en": "Schweppes, lillet, ice",
        "desc_hu": "Schweppes, lillet, jég",
        "weight": "250ml",
    },
    {
        "id": "cocktail-6", "category": "cocktail", "price": 23,
        "name_ro": "Gin Tonic", "name_en": "Gin Tonic", "name_hu": "Gin Tonic",
        "desc_ro": "Dry gin, evervess bitter, lămâie, gheață",
        "desc_en": "Dry gin, evervess bitter, lemon, ice",
        "desc_hu": "Dry gin, evervess bitter, citrom, jég",
        "weight": "250ml",
    },

    # ─── VINURI ───────────────────────────────────────────────
    {
        "id": "wine-1", "category": "wine", "price": 85,
        "name_ro": "Fort Silvan 47 Merlot Sec 750ml", "name_en": "Fort Silvan 47 Merlot Dry 750ml", "name_hu": "Fort Silvan 47 Merlot Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-2", "category": "wine", "price": 70,
        "name_ro": "Fort Silvan Venator Pinot Noir Sec 50ml", "name_en": "Fort Silvan Venator Pinot Noir Dry 50ml", "name_hu": "Fort Silvan Venator Pinot Noir Száraz 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "wine-3", "category": "wine", "price": 70,
        "name_ro": "Fort Silvan Fetească Regală Sec 750ml", "name_en": "Fort Silvan Feteasca Regala Dry 750ml", "name_hu": "Fort Silvan Fetească Regală Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-4", "category": "wine", "price": 70,
        "name_ro": "Fort Silvan Stephanus Sec 750ml", "name_en": "Fort Silvan Stephanus Dry 750ml", "name_hu": "Fort Silvan Stephanus Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-5", "category": "wine", "price": 70,
        "name_ro": "Fort Silvan Traminer Sec 750ml", "name_en": "Fort Silvan Traminer Dry 750ml", "name_hu": "Fort Silvan Traminer Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-6", "category": "wine", "price": 70,
        "name_ro": "Fort Silvan Rose Sec 750ml", "name_en": "Fort Silvan Rose Dry 750ml", "name_hu": "Fort Silvan Rosé Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-7", "category": "wine", "price": 70,
        "name_ro": "Balla Geza Fetească Neagră Sec 750ml", "name_en": "Balla Geza Feteasca Neagra Dry 750ml", "name_hu": "Balla Géza Fekete Leányka Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-8", "category": "wine", "price": 70,
        "name_ro": "Balla Geza Cadarcă Sec 750ml", "name_en": "Balla Geza Kadarka Dry 750ml", "name_hu": "Balla Géza Kadarka Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-9", "category": "wine", "price": 100,
        "name_ro": "Balla Geza Stone Wine Cadarcă & Fetească Neagră Sec 750ml", "name_en": "Balla Geza Stone Wine Kadarka & Feteasca Neagra Dry 750ml", "name_hu": "Balla Géza Stone Wine Kadarka & Fekete Leányka Száraz 750ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "750ml",
    },
    {
        "id": "wine-10", "category": "wine", "price": 75,
        "name_ro": "Purcari 750ml", "name_en": "Purcari 750ml", "name_hu": "Purcari 750ml",
        "desc_ro": "Rară neagră, sauvignon blanc, chardonnay, sec",
        "desc_en": "Rara neagra, sauvignon blanc, chardonnay, dry",
        "desc_hu": "Rară neagră, sauvignon blanc, chardonnay, száraz",
        "weight": "750ml",
    },
    {
        "id": "wine-11", "category": "wine", "price": 15,
        "name_ro": "Mini Vin Alb/Roșu/Rosé 187ml", "name_en": "Mini Wine White/Red/Rosé 187ml", "name_hu": "Mini Bor Fehér/Vörös/Rosé 187ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "187ml",
    },
    {
        "id": "wine-12", "category": "wine", "price": 10,
        "name_ro": "Vin la Pahar 200ml", "name_en": "Wine by Glass 200ml", "name_hu": "Pohár Bor 200ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "200ml",
    },

    # ─── BĂUTURI SCURTE ───────────────────────────────────────
    {
        "id": "short-1", "category": "short_drink", "price": 10,
        "name_ro": "Jagermeister 40ml", "name_en": "Jagermeister 40ml", "name_hu": "Jagermeister 40ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "40ml",
    },
    {
        "id": "short-2", "category": "short_drink", "price": 14,
        "name_ro": "Jack Daniels 50ml", "name_en": "Jack Daniels 50ml", "name_hu": "Jack Daniels 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-3", "category": "short_drink", "price": 15,
        "name_ro": "Honey Jack 50ml", "name_en": "Honey Jack 50ml", "name_hu": "Honey Jack 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-4", "category": "short_drink", "price": 20,
        "name_ro": "Jack Single Barrel 50ml", "name_en": "Jack Single Barrel 50ml", "name_hu": "Jack Single Barrel 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-5", "category": "short_drink", "price": 10,
        "name_ro": "Alexandrion 50ml", "name_en": "Alexandrion 50ml", "name_hu": "Alexandrion 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-6", "category": "short_drink", "price": 12,
        "name_ro": "Jidvei 50ml", "name_en": "Jidvei 50ml", "name_hu": "Jidvei 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-7", "category": "short_drink", "price": 10,
        "name_ro": "Vodka 50ml", "name_en": "Vodka 50ml", "name_hu": "Vodka 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-8", "category": "short_drink", "price": 10,
        "name_ro": "Tequila 40ml", "name_en": "Tequila 40ml", "name_hu": "Tequila 40ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "40ml",
    },
    {
        "id": "short-9", "category": "short_drink", "price": 15,
        "name_ro": "Unicum 50ml", "name_en": "Unicum 50ml", "name_hu": "Unicum 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
    {
        "id": "short-10", "category": "short_drink", "price": 15,
        "name_ro": "Courvaiser Coniac 50ml", "name_en": "Courvaiser Cognac 50ml", "name_hu": "Courvaiser Konyak 50ml",
        "desc_ro": "", "desc_en": "", "desc_hu": "",
        "weight": "50ml",
    },
]

EXTRAS = [
    {"id": "extra-beef", "category": "burger", "price": 16, "name_ro": "Carne de Vită Black Angus (Burger Dublu)", "name_en": "Black Angus Beef (Double Burger)", "name_hu": "Black Angus Marhahús (Dupla Burger)", "weight": "130g"},
    {"id": "extra-cheese", "category": "burger", "price": 6, "name_ro": "Cheddar / Blue Cheese / Camembert / Pancetta / Ceapă Caramelizată", "name_en": "Cheddar / Blue Cheese / Camembert / Pancetta / Caramelized Onion", "name_hu": "Cheddar / Blue Cheese / Camembert / Pancetta / Karamellizált Hagyma", "weight": "20g"},
    {"id": "extra-sauce-classic", "category": "burger", "price": 5, "name_ro": "Sos Usturoi / Classic / Cheddar / BBQ / Ketchup / Sweet Chilli", "name_en": "Garlic / Classic / Cheddar / BBQ / Ketchup / Sweet Chilli Sauce", "name_hu": "Fokhagyma / Classic / Cheddar / BBQ / Ketchup / Sweet Chilli Szósz", "weight": "50ml"},
    {"id": "extra-sauce-mushroom", "category": "burger", "price": 9, "name_ro": "Sos de Ciuperci", "name_en": "Mushroom Sauce", "name_hu": "Gombaszósz", "weight": "50ml"},
    {"id": "extra-pizza-topping", "category": "pizza", "price": 6, "name_ro": "Mozzarella / Salam / Șuncă / Piept de Pui", "name_en": "Mozzarella / Salami / Ham / Chicken Breast", "name_hu": "Mozzarella / Szalámi / Sonka / Csirkemell", "weight": "50g"},
    {"id": "extra-pizza-veg", "category": "pizza", "price": 5, "name_ro": "Ciuperci / Porumb / Ceapă / Jalapeno", "name_en": "Mushrooms / Corn / Onion / Jalapeno", "name_hu": "Gomba / Kukorica / Hagyma / Jalapeno", "weight": "40g"},
    {"id": "extra-pizza-sauce", "category": "pizza", "price": 5, "name_ro": "Sos Usturoi / Classic / Roșii / Ketchup", "name_en": "Garlic / Classic / Tomato / Ketchup Sauce", "name_hu": "Fokhagyma / Classic / Paradicsom / Ketchup Szósz", "weight": "50ml"},
    {"id": "extra-pizza-mushroom", "category": "pizza", "price": 9, "name_ro": "Sos de Ciuperci", "name_en": "Mushroom Sauce", "name_hu": "Gombaszósz", "weight": "50ml"},
]

CATEGORY_IMAGES = {}
ITEM_IMAGES = {}
DRINK_RECOMMENDATIONS = {}